resources:
  - kind: cloudresourcemanager.googleapis.com/Project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".name"
          blueprint: '"gcpProject"'
          title: ".display_name"
  - kind: container.googleapis.com/Cluster
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".id"
          blueprint: '"gcpontainerCluster"'
          title: ".name"
          properties:
            description: ".description"
            currentNodeCount: ".currentNodeCount"
            currentNodeVersion: ".currentNodeVersion"
            initialNodeCount: ".initialNodeCount"
            location: ".location"
          relations:
            project: ".project"
  - kind: cloudfunctions.googleapis.com/CloudFunction
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".name"
          blueprint: '"gcpCloudFunctions"'
          title: ".name"
          properties:
            url: ".url"
            state: ".state"
            environment: ".environment"
            eventTrigger: ".eventTrigger"
          relations:
            project: ".project"
  - kind: pubsub.googleapis.com/Topic
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".name"
          blueprint: '"gcpTopics"'
          title: '.name | split("/") | .[-1]'
          properties:
            state: ".state"
            schemaSettings: ".schema_settings"
            messageRetentionDuration: ".message_retention_duration"
          relations:
            project: ".__project.name"
  - kind: cloudResource
    selector:
      query: "true"
      resourceKinds:
        [
          "compute.googleapis.com/Disk",
          "pubsub.googleapis.com/Subscription",
          "iam.googleapis.com/ServiceAccount",
        ]
    port:
      entity:
        mappings:
          identifier: ".name"
          title: '.name | split("/") | last'
          blueprint: '"gcpCloudResource"'
          properties:
            type: ".asset_type"
            location: ".location"
          relations:
            project: ".project"
