resources:
  - kind: AWS::EC2::Instance
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .InstanceId
          title: .KeyName
          blueprint: '"ec2"'
          properties:
            architecture: .Architecture
  - kind: cloudresource
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .Identifier
          title: .Identifier
          blueprint: '"cloud_resource"'
          properties:
            kind: .Kind
