resources:
  - kind: AWS::Organizations::Account
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .Id
          title: .Name
          blueprint: '"awsAccount"'
          properties:
            arn: .Arn
            email: .Email
            status: .Status
            joined_method: .JoinedMethod
            joined_timestamp: .JoinedTimestamp

  - kind: cloudResource
    selector:
      query: 'true'
      resourceKinds:
        - AWS::Lambda::Function
        - AWS::RDS::DBInstance
        - AWS::S3::Bucket
        - AWS::IAM::User
        - AWS::ECS::Cluster
        - AWS::ECS::Service
        - AWS::Logs::LogGroup
        - AWS::DynamoDB::Table
        - AWS::SQS::Queue
        - AWS::SNS::Topic
        - AWS::Cognito::IdentityPool
        - AWS::CloudFormation::Stack
    port:
      entity:
        mappings:
          identifier: .Identifier
          title: .Identifier
          blueprint: '"cloudResource"'
          properties:
            kind: .__Kind
            region: .__Region
            tags: .Properties.Tags
            arn: .Properties.Arn
            link: '.Properties | select(.Arn != null) | "https://console.aws.amazon.com/go/view?arn=" + .Arn'
          relations:
            account: .__AccountId
