resources:
  - kind: AWS::EC2::Instance
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .InstanceId
          title: .KeyName
          blueprint: '"ec2"'
          properties:
            architecture: .Architecture
  - kind: AWS::Lambda::Function
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: '.FunctionName'
          title: '.FunctionName'
          blueprint: '"lambda"'
          properties:
            link: '"https://console.aws.amazon.com/go/view?arn=" + .Arn'
            description: '.Description'
            memorySize: '.MemorySize'
            ephemeralStorageSize: '.EphemeralStorage.Size'
            timeout: '.Timeout'
            runtime: '.Runtime'
            packageType: '.PackageType'
            environment: '.Environment'
            architectures: '.Architectures'
            layers: '.Layers'
            tags: '.Tags'
            iamRole: '"https://console.aws.amazon.com/go/view?arn=" + .Role'
            arn: '.Arn'
  - kind: cloudresource
    selector:
      query: 'true'
      resourceKinds:
        - AWS::Lambda::Function
        - AWS::RDS::DBInstance
        - AWS::S3::Bucket
        - AWS::IAM::User
        - AWS::ECS::Cluster
        - AWS::ECS::Service
        - AWS::Logs::LogGroup
        - AWS::DynamoDB::Table
        - AWS::SQS::Queue
        - AWS::SNS::Topic
        - AWS::Cognito::IdentityPool
        - AWS::CloudFormation::Stack
    port:
      entity:
        mappings:
          identifier: .Identifier
          title: .Identifier
          blueprint: '"cloud_resource"'
          properties:
            kind: .Kind
