resources:
  - kind: ec2
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .InstanceId
          title: .KeyName
          blueprint: '"ec2"'
          properties:
            architecture: .Architecture
  - kind: cloudResource
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .Identifier
          title: .Identifier
          blueprint: '"cloudResource"'
          properties:
            kind: .Kind
