resources:
  - kind: AWS::Organizations::Account
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .Id
          title: .Name
          blueprint: '"aws_account"'

  - kind: cloudResource
    selector:
      query: 'true'
      resourceKinds:
        - AWS::Lambda::Function
        - AWS::RDS::DBInstance
        - AWS::S3::Bucket
        - AWS::IAM::User
        - AWS::ECS::Cluster
        - AWS::ECS::Service
        - AWS::Logs::LogGroup
        - AWS::DynamoDB::Table
        - AWS::SQS::Queue
        - AWS::SNS::Topic
        - AWS::Cognito::IdentityPool
        - AWS::CloudFormation::Stack

    port:
      entity:
        mappings:
          identifier: .Identifier
          title: .Identifier
          blueprint: '"cloud_resource"'
          properties:
            kind: .__Kind
            region: .__Region
            tags: .Tags
            arn: .Arn
            link: 'if has("Arn") then "https://console.aws.amazon.com/go/view?arn=" + .Arn else empty end'
          relations:
            account: .__AccountId
