createMissingRelatedEntities: True
resources:
  - kind: amplication_template
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"AmplicationTemplate"'
          properties:
            name: .name
            description: .description
            project: .project.name
            project_id: .project.id
            blueprint: .blueprint.name
            blueprint_id: .blueprint.id
  - kind: amplication_resource
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"AmplicationResource"'
          properties:
            name: .name
            description: .description
            project: .project.name
            project_id: .project.id
            blueprint: .blueprint.name
            blueprint_id: .blueprint.id
            git_organization: .gitRepository.gitOrganization.provider
            git_repository: '.gitRepository.gitOrganization.name + "/" + .gitRepository.name'
          relations:
            template: if .serviceTemplate != null and .serviceTemplate != "None" then .serviceTemplate.id else null end
  - kind: amplication_alert
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: '.type + ": " + .block.displayName'
          blueprint: '"AmplicationAlert"'
          properties:
            block_id: .block.id
            block_displayName: .block.displayName
            type: .type
            outdatedVersion: .outdatedVersion
            latestVersion: .latestVersion
            status: .status
          relations:
            resource: .resourceId
