createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: space
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .Id
          title: .Name
          blueprint: '"octopusSpace"'
          properties:
            url: "\"https://testport.octopus.app/app#/\" + .Id"
            description: .Description
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .Id
          title: .Name
          blueprint: '"octopusProject"'
          properties:
            url: "\"https://testport.octopus.app/app#/\" + .SpaceId + \"/projects/\" + .Id"
            description: .Description
            isDisabled: .IsDisabled
            tenantedDeploymentMode: .TenantedDeploymentMode
          relations:
            space: .SpaceId
  - kind: release
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .Id
          title: ".Version + \"(\" + .ProjectId + \")\""
          blueprint: '"octopusRelease"'
          properties:
            version: .Version
            assembledDate: .Assembled
            channelId: .ChannelId
            releaseNotes: .ReleaseNotes
            url: "\"https://testport.octopus.app/app#/\" + .SpaceId + \"/releases/\" + .Id"
          relations:
            project: .ProjectId
            space: .SpaceId
  - kind: deployment
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .Id
          title: .Name
          blueprint: '"octopusDeployment"'
          properties:
            createdAt: .Created
            deployedBy: .DeployedBy
            taskId: .TaskId
            failureEncountered: .FailureEncountered
            comments: .Comments
            url: "\"https://testport.octopus.app/app#/\" + .SpaceId + \"/deployments/\" + .Id"
          relations:
            release: .ReleaseId
            project: .ProjectId
            space: .SpaceId
  - kind: machine
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .Id
          title: .Name
          blueprint: '"octopusMachine"'
          properties:
            roles: .Roles
            status: .HealthStatus
            url: "\"https://testport.octopus.app/app#/\" + .SpaceId + \"/infrastructure/machines/\" + .Id + \"/settings\""
            isDisabled: .IsDisabled
            operatingSystem: .OperatingSystem
            architecture: .Architecture
            statusSummary: .StatusSummary
            endpointType: .Endpoint.DeploymentTargetTypeId
            communicationStyle: .Endpoint.CommunicationStyle
          relations:
            space: .SpaceId
