initializePortResources: true
port:
  clientId: "{{ from env PORT_CLIENT_ID }}"
  clientSecret: "{{ from env PORT_CLIENT_SECRET }}"
eventListener:
  type: POLLING
integration:
  identifier: "{{ from env INTEGRATION_IDENTIFIER }}"
  type: "gcp"
  config:
    parent: "{{ from env PARENT }}"
    serviceAccountFileLocation: "{{ from env SERVICE_ACCOUNT_FILE_LOCATION }}"
    assetsFeedId: "{{ from env ASSETS_FEED_ID }}"
    assetsFeedAssetTypes: "{{ from env ASSETS_FEED_ASSET_TYPES }}"
    assetsFeedTopicName: "{{ from env ASSETS_FEED_TOPIC_NAME }}"
