initializePortResources: true
port:
  clientId: "{{ from env PORT_CLIENT_ID }}"
  clientSecret: "{{ from env PORT_CLIENT_SECRET }}"
eventListener:
  type: POLLING
integration:
  identifier: "my-gcp-integration"
  type: "gcp"
  config:
    parent: "{{ from env PARENT }}"
    serviceAccountFileLocation: "{{ from env SERVICE_ACCOUNT_FILE_LOCATION }}"
