createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: team
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .node.key
          title: .node.name
          blueprint: '"linearTeam"'
          properties:
            description: .node.description
            workspaceName: .node.organization.name
            url: "\"https://linear.app/\" + .node.organization.urlKey + \"/team/\" + .node.key"
  - kind: label
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .node.id
          title: .node.name
          blueprint: '"linearLabel"'
          properties:
            isGroup: .node.isGroup
          relations:
            parentLabel: .node.parent.id
            childLabels: "[.node.children.edges[].node.id]"
  - kind: issue
    selector:
      query: "true"
      # jql: "status != Done"
    port:
      entity:
        mappings:
          identifier: .node.identifier
          title: .node.title
          blueprint: '"linearIssue"'
          properties:
            url: .node.url
            status: .node.state.name
            assignee: .node.assignee.email
            creator: .node.creator.email
            priority: .node.priorityLabel
            created: .node.createdAt
            updated: .node.updatedAt
          relations:
            team: .node.team.key
            labels: .node.labelIds
            parentIssue: .node.parent.identifier
