initializePortResources: true
port:
  clientId: "{{ from env PORT_CLIENT_ID }}"   # Can be loaded via environment variable: PORT_CLIENT_ID
  clientSecret: "{{ from env PORT_CLIENT_SECRET }}"   # Can be loaded via environment variable: PORT_CLIENT_SECRET
# The event listener to use for the integration service.
eventListener:
  type: POLLING
integration:
  # The identifier of this integration instance.
  identifier: "my-wiz-integration"
  # The type of the integration.
  type: "wiz"
  config:
    wizClientId: "{{ from env WIZ_CLIENT_ID }}"
    wizClientSecret: "{{ from env WIZ_CLIENT_SECRET }}"
    wizTokenUrl: "{{ from env WIZ_TOKEN_URL }}"
    wizApiUrl: "{{ from env WIZ_API_URL }}"
    wizWebhookVerificationToken: "{{ from env WIZ_WEBHOOK_TOKEN }}"
