deleteDependentEntities: true
createMissingRelatedEntities: true
resources:
  - kind: cluster
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .name
          title: .name
          blueprint: '"argocdCluster"'
          properties:
            applicationsCount: .info.applicationsCount
            serverVersion: .serverVersion
            labels: .labels
            updatedAt: .connectionState.attemptedAt
            server: .server
          relations:
            namespace: .namespaces
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .metadata.name
          title: .metadata.name
          blueprint: '"argocdProject"'
          properties:
            namespace: .metadata.namespace
            createdAt: .metadata.creationTimestamp
            description: .spec.description
          relations:
            cluster: '[.spec.destinations[].name | select(test("^[a-zA-Z0-9@_.:/=-]+$"))]'
  - kind: application
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .metadata.uid
          title: .metadata.name
          blueprint: '"argocdApplication"'
          properties:
            gitRepo: .spec.source.repoURL
            gitPath: .spec.source.path
            destinationServer: .spec.destination.server
            revision: .status.sync.revision
            targetRevision: .spec.source.targetRevision
            syncStatus: .status.sync.status
            healthStatus: .status.health.status
            createdAt: .metadata.creationTimestamp
          relations:
            project: .spec.project
            namespace: .metadata.namespace
            cluster: .spec.destination.name
  - kind: deployment-history
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .__applicationId + "-" + (.id | tostring)
          title: .id | tostring
          blueprint: '"argocdDeploymentHistory"'
          properties:
            deployedAt: .deployedAt
            deployStartedAt: .deployStartedAt
            revision: .source.repoURL + "/commit/" + .revision
            initiatedBy: .initiatedBy.username
            repoURL: .source.repoURL
            sourcePath: .source.path
          relations:
            application: .__applicationId
  - kind: kubernetes-resource
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .__applicationId + "-" + .name
          title: .name
          blueprint: '"argocdKubernetesResource"'
          properties:
            kind: .kind
            version: .version
            namespace: .namespace
            syncStatus: .status
            healthStatus: .health.status
          relations:
            application: .__applicationId
