createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: user
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .email
          title: .user.name
          blueprint: '"sentryUser"'
          properties:
            username: .user.username
            isActive: .user.isActive
            dateJoined: .user.dateJoined
            lastLogin: .user.lastLogin
            orgRole: .orgRole
            inviteStatus: .inviteStatus
  - kind: team
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .slug
          title: .name
          blueprint: '"sentryTeam"'
          properties:
            dateCreated: .dateCreated
            memberCount: .memberCount
            roles: .teamRole
  - kind: project-tag
    selector:
      query: "true"
      tag: "environment"
    port:
      entity:
        mappings:
          identifier: .slug + "-" + .__tags.name
          title: .name + "-" + .__tags.name
          blueprint: '"sentryProject"'
          properties:
            dateCreated: .dateCreated
            platform: .platform
            status: .status
            link: .organization.links.organizationUrl + "/projects/" + .name
  - kind: issue-tag
    selector:
      query: "true"
      tag: "environment"
    port:
      entity:
        mappings:
          identifier: .id
          title: .title
          blueprint: '"sentryIssue"'
          properties:
            link: .permalink
            status: .status
            isUnhandled: .isUnhandled
          relations:
            projectEnvironment: '[(.project.slug as $slug | .__tags[] | "\($slug)-\(.name)")]'
            assignedTo: .assignedTo.email
