initializePortResources: true
port:
  # The event listener to use for the integration service.
  orgId: "{{ from env PORT_ORG_ID }}"
  clientId: "{{ from env PORT_CLIENT_ID }}"
  clientSecret: "{{ from env PORT_CLIENT_SECRET }}"
eventListener:
  type: POLLING
integration:
  # The identifier of this integration instance.
  identifier: "terraform"
  # The type of the integration.
  type: "terraform"
  config:
    terraformHost: "{{ from env TERRAFORM_HOST }}"
    terraformOrganization: "{{ from env TERRAFORM_ORGANIZATION}}"
    terraformToken: "{{ from env TERRAFORM_TOKEN }}"