# This is an example configuration file for the integration service.
# Please copy this file to conf/config.yaml and edit it to your needs.

# The integrations list to load into the integration port_ocean.
# You can add as many integrations as you want, and you can use the same type of integration multiple times.
port:
  clientId: 60EsooJtOqimlekxrNh7nfr2iOgTcyLZ # Can be loaded via environment variable: PORT_CLIENT_ID, if both are set, the environment variable will be used.
  clientSecret: ouumHo0FKZtkDQyOgY2NAFrAGpBeWMQ1I9CCj1VJxYeEZqGGy11TVHBpoSn3dB9J # Can be loaded via environment variable: PORT_CLIENT_SECRET, if both are set, the environment variable will be used.
  baseUrl: http://localhost:3000/v1 # Can be loaded via environment variable: PORT_BASE_URL, if both are set, the environment variable will be used.
# The trigger channel to use for the integration service.
triggerChannel:
  type: WEBHOOK
  appHost: https://cdf8-81-199-132-66.ngrok-free.app
#  brokers: "localhost:9092"
#  kafkaSecurityEnabled: false
integration:
  # The name of the integration.
  identifier: "my_integration"
  # The type of the integration.
  type: "Gitlab"
  # The configuration of the integration.
  # resyncOnStartup: true
  config:
    tokenMapping: {"glpat-Y7DTQnHuFopsM3o73XJ9":["getport-labs/**"]}
    appHost: https://cdf8-81-199-132-66.ngrok-free.app
