createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: job
    selector:
      query: "true"
    port:
      entity:
        mappings:
          blueprint: '"job"'
          identifier: .url
          title: .name
          properties:
            name: .name
            url: .url
            status: .status
            timestamp: .timestamp
  - kind: build
    selector:
      query: "true"
    port:
      entity:
        mappings:
          blueprint: build
          identifier: .url
          identifier: .url
          title: .name
          properties:
            id: .id
            name: .name
            status: .status
            url: .url
            timestamp: .timestamp
            duration: .duration
            jobUrl: .jobUrl
          relations:
            job: .jobUrl
