createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: job
    selector:
      query: "true"
    port:
      entity:
        mappings:
          blueprint: '"job"'
          identifier: .name
          title: .name
          properties:
            name: .name
            url: .url
            status: .lastBuild.result
            timestamp: '.timestamp |= (. / 1000 | strftime("%Y-%m-%d %H:%M:%S %Z"))'

  - kind: build
    selector:
      query: "true"
    port:
      entity:
        mappings:
          blueprint: '"build"'
          identifier: .fullDisplayName
          title: .fullDisplayName
          properties:
            id: .id
            name: .fullDisplayName
            status: .result
            url: .url
            timestamp: '.timestamp |= (. / 1000 | strftime("%Y-%m-%d %H:%M:%S %Z"))'
            duration: '.duration |= (. / 1000 | sprintf("%.2fsec"))'
            job: '.url |= (. | sub("/[0-9]+/$"; ""))'
          relations:
            job: '.url |= (. | sub("/[0-9]+/$"; ""))'
