resources:
  - kind: list
    selector:
      query: .name | <your-team-list-name>
    port:
      itemsToParse: .items
      entity:
        mappings:
          blueprint: '"_team"'
          identifier: .item.id
          title: .item.name
  - kind: profile
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .email
          blueprint: '"_user"'
          relations:
            teams: <your-team-list-name>
