resources:
  - kind: profile
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .email
          blueprint: '"HiBobUser"'
          properties:
            name: .displayName
            tenure: .tenureDuration.humanize
            is_manager: .isManager
          relations:
            teams: .department
            reportsTo: .reportsTo.email
