resources:
  - kind: workspace
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .attributes.name
          blueprint: '"terraformWorkspace"'
          properties:
            workspaceName: .attributes.name
            createdAt: .attributes."created-at"
            updatedAt: .attributes."updated-at"
            terraformVersion: .attributes."terraform-version"
            locked: .attributes.locked
            executionMode: .attributes."execution-mode"
            resourceCount: .attributes."resource-count"
            latestChangeAt: .attributes."latest-change-at"

  - kind: run
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .attributes.message
          blueprint: '"terraformRun"'
          properties:
            runId: .id
            createdAt: .attributes."created-at"
            status: .attributes.status
            hasChanges: .attributes."has-changes"
            isDestroy: .attributes."is-destroy"
            message: .attributes.message
            terraformVersion: .attributes."terraform-version"
            appliedAt: .attributes."status-timestamps"."applied-at"
            plannedAt: .attributes."status-timestamps"."planned-at"
            source: .attributes.source
          relations: 
            terraformWorkspace: .relationships.workspace.data.id
