# initializePortResources: true
# port:
#   clientId: '{{ from env PORT_CLIENT_ID }}'
#   clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
# eventListener:
#   type: POLLING
# integration:
#   identifier: my-terraform-cloud-integration
#   type: terraform-cloud
#   config:
#     terraformCloudHost: '{{ from env TERRAFORM_CLOUD_HOST }}'
#     terraformCloudToken: '{{ from env TERRAFORM_ClOUD_TOKEN }}'
#     appHost: '{{ from env APP_HOST }}'

initializePortResources: true
port:
  # The event listener to use for the integration service.
  orgId: "org_X7mr3YufDQf6gJKw" #"{{ from env PORT_ORG_ID }}"
  clientId: "9BSlAex5gW8JRt6OwB93f7W5fxtiduCF" #"{{ from env PORT_CLIENT_ID }}"
  clientSecret: "ZEPtwlXHZ1fgRJdDi89NCiaJkpyseY7C3lx5IehjtwN3lbcmN377K9AhCTLut6fD" #"{{ from env PORT_CLIENT_SECRET }}"
eventListener:
  type: POLLING
integration:
  # The identifier of this integration instance.
  identifier: "my-terraform-cloud-integration"
  # The type of the integration.
  type: "terraform"
  config:
    terraformCloudHost: "https://app.terraform.io" #"{{ from env TERRAFORM_HOST }}"
    terraformCloudToken: "CJqqhEqgXMzolg.atlasv1.E8GZ0mj1zBAkfQiyYyzb1VlZyE6SaTDJavEj1bbhhzvM2kIwS6u4vgDdFZqYrlEncy4" #"{{ from env TERRAFORM_TOKEN }}"
    # appHost: "https://9d68-45-222-192-146.ngrok-free.app"