initializePortResources: true
port:
  orgId: '{{ from env PORT_ORG_ID }}'
  clientId: '{{ from env PORT_CLIENT_ID }}'
  clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
eventListener:
  type: POLLING
integration:
  identifier: my-terraform-cloud-integration
  type: terraform-cloud
  config:
    terraformCloudHost: '{{ from env TERRAFORM_CLOUD_HOST }}'
    terraformCloudToken: '{{ from env TERRAFORM_CLOUD_TOKEN }}'
    appHost: '{{ from env APP_HOST }}'