initializePortResources: true
port:
  orgId: '{{ from env PORT_ORG_ID }}'
  clientId: '{{ from env PORT_CLIENT_ID }}'
  clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
eventListener:
  type: POLLING
integration:
  identifier: my-terraform-integration
  type: terraform-cloud
  config:
    terraformHost: '{{ from env TERRAFORM_HOST }}'
    terraformOrganization: '{{ from env TERRAFORM_ORGANIZATION}}'
    terraformToken: '{{ from env TERRAFORM_TOKEN }}'
    appHost: '{{ from env APP_HOST }}'
