initializePortResources: true
port:
  orgId: '{{ from env PORT_ORG_ID }}'
  clientId: '{{ from env PORT_CLIENT_ID }}'
  clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
eventListener:
  type: POLLING
integration:
  identifier: my-terraform-integration
  type: terraform-cloud
  config:
    terraformHost: '{{ from env TERRAFORM_HOST }}'
    terraformOrganization: '{{ from env TERRAFORM_ORGANIZATION}}'
    terraformToken: '{{ from env TERRAFORM_TOKEN }}'
    appHost: '{{ from env APP_HOST }}'



# initializePortResources: true
# port:
#   # The event listener to use for the integration service.
#   orgId: "org_X7mr3YufDQf6gJKw" #"{{ from env PORT_ORG_ID }}"
#   clientId: "9BSlAex5gW8JRt6OwB93f7W5fxtiduCF" #"{{ from env PORT_CLIENT_ID }}"
#   clientSecret: "ZEPtwlXHZ1fgRJdDi89NCiaJkpyseY7C3lx5IehjtwN3lbcmN377K9AhCTLut6fD" #"{{ from env PORT_CLIENT_SECRET }}"
# eventListener:
#   type: POLLING
# integration:
#   # The identifier of this integration instance.
#   identifier: "terraform"
#   # The type of the integration.
#   type: "terraform"
#   config:
#     terraformHost: "https://app.terraform.io" #"{{ from env TERRAFORM_HOST }}"
#     terraformOrganization: "example-org-162af6" # "{{ from env TERRAFORM_ORGANIZATION}}"
#     terraformToken: "JBdUgQ93Rw6NOg.atlasv1.pvMGBx7IChZCcagS16fge7K7E7ms7cO9tbXtXy5dAQD6tVbyuDFrhLD5s0s2lluJTmk" #"{{ from env TERRAFORM_TOKEN }}"