site_name: Ocean API References
site_url: https://app.getport.io
theme:
  name: material
  logo: ./assets/OceanSymbol.svg
  favicon: ./assets/OceanSymbol.svg
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.tabs

  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

repo_name: port-labs/Port-Ocean
repo_url: https://github.com/port-labs/Port-Ocean
docs_dir: src

# Plugins
plugins:
  - redirects:
      redirect_maps:
          'index.md': 'references/index.md'
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          paths: [../../port_ocean]
          options:
            show_root_heading: true
            heading_level: 2
            show_category_heading: true
            show_source: false
            show_bases: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      linenums: True
      guess_lang: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: ../
  - attr_list:
  - md_in_html:

extra_css:
  - assets/css/termynal.css
  - assets/css/custom.css
extra_javascript:
  - assets/js/termynal.js
  - assets/js/custom.js

nav:
   - 🔍 References:
       - References: ./references/index.md
       - core:
           - integrations:
               - ./references/core/integrations/index.md
               - mixins: ./references/core/integrations/mixins.md
           - handlers:
               - entities_state_applier: ./references/core/handlers/entities-state-applier.md
               - entity_processor: ./references/core/handlers/entity-processor.md
               - port_app_config: ./references/core/handlers/port-app-config.md
           - event_listener:
               - ./references/core/event-listener/index.md
               - polling: ./references/core/event-listener/polling.md
               - kafka: ./references/core/event-listener/kafka.md
               - http: ./references/core/event-listener/http.md
           - models: ./references/core/models.md
           - ocean_types: ./references/core/ocean-types.md
       - clients: ./references/clients.md
       - config: ./references/config.md
       - consumers: ./references/consumers.md
       - context: ./references/context.md
       - middleware: ./references/middleware.md
       - ocean: ./references/ocean.md
       - run: ./references/run.md
       - utils: ./references/utils.md
   - 🌊 Ocean Guides: https://ocean.getport.io
