initializePortResources: true
port:
  clientId: '{{ from env PORT_CLIENT_ID }}'
  clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
eventListener:
  type: POLLING
integration:
  identifier: 'my-launchdarkly-integration'
  type: 'launchdarkly'
  config:
    launchdarklyToken: '{{ from env LAUNCHDARKLY_TOKEN }}'
    launchdarklyHost: '{{ from env LAUNCHDARKLY_HOST }}'
    appHost: '{{ from env APP_HOST }}'
