port:
  clientId: '{{ from env PORT_CLIENT_ID }}'
  clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
eventListener:
  type: POLLING
integration:
  identifier: 'my-aws-integration'
  type: 'aws'
  config: {}
