port:
  clientId: '{{ from env PORT_CLIENT_ID }}'
  clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
eventListener:
  type: POLLING
integration:
  identifier: 'azure'
  type: 'azure'
  config:
    awsAccessKeyId: '{{ from env AWS_ACCESS_KEY_ID }}'
    awsSecretAccessKey: '{{ from env AWS_SECRET_ACCESS_KEY }}'
    awsApiKey: '{{ from env AWS_API_KEY }}'
    awsRegions: '{{ from env AWS_REGIONS }}'
    organizationRoleArn: '{{ from env ORGANIZATION_ROLE_ARN }}'
    accountReadRoleName: '{{ from env ACCOUNT_READ_ROLE_NAME }}'
