port:
  clientId: '{{ from env PORT_CLIENT_ID }}'
  clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
eventListener:
  type: POLLING
integration:
  identifier: '{{ from env INTEGRATION_IDENTIFIER }}'
  type: '{{ from env INTEGRATION_TYPE }}'
  config:
    awsAccessKeyId: '{{ from env AWS_ACCESS_KEY_ID }}'
    awsSecretAccessKey: '{{ from env AWS_SECRET_ACCESS_KEY }}'
    awsRegions: '{{ from env AWS_REGIONS }}'
