port:
  clientId: '{{ from env PORT_CLIENT_ID }}'
  clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
eventListener:
  type: POLLING
integration:
  identifier: 'AWS'
  type: 'aws'
  config:
    awsApiKey: '{{ from env AWS_API_KEY }}'
    awsAccessKeyId: '{{ from env AWS_ACCESS_KEY_ID }}'
    awsSecretAccessKey: '{{ from env AWS_SECRET_ACCESS_KEY }}'
    awsRegions: '{{ from env AWS_REGIONS }}'
