resources:
  - kind: gitlabGroup
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"gitlabGroup"'
          properties:
            visibility: .visibility
            url: .web_url
            description: .description


  - kind: gitlabProject
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"gitlabProject"'
          properties:
            url: .web_url
            readme: .readme
            description: .description
            language: .__languages | to_entries | max_by(.value) | .key
            namespace: .namespace
            fullPath: .full_path
            defaultBranch: .default_branch
        relations:
          group: .namespace.id


  - kind: gitlabMergeRequest
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .title
          blueprint: '"gitlabMergeRequest"'
          properties:
            creator: .author.username
            status: .state
            createdAt: .created_at
            updatedAt: .updated_at
            mergedAt: .merged_at
            link: .web_url
            reviewers: '.reviewers[] | .username'
        relations:
          project: .namespace.id


  - kind: gitlabIssue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .title
          blueprint: '"gitlabIssue"'
          properties:
            link: .web_url
            description: .description
            createdAt: .created_at
            closedAt: .closed_at
            updatedAt: .updated_at
            creator: .author.username
            status: .state
            labels: '.labels[]'
        relations:
          project: .namespace.id
