resources:
  - kind: gitlabGroup
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"gitlabGroup"'
          properties:
            visibility: .visibility
            url: .web_url
            description: .description

  - kind: gitlabProject
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"gitlabProject"'
          properties:
            validity: .validity
            url: .projectUrl
        relations:
          group:
            target:
              identifier: .namespace.id
              blueprint: '"gitlabGroup"'


  - kind: gitlabMergeRequest
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .title
          blueprint: '"gitlabMergeRequest"'
          properties:
            creator: .author.username
            status: .state
            createdAt: .created_at
            updatedAt: .updated_at
            mergedAt: .merged_at
            link: .web_url
            reviewers: '.reviewers[] | .username'
        relations:
          service:
            target:
              identifier: .project_id
              blueprint: '"project"'


  - kind: gitlabIssue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .title
          blueprint: '"gitlabIssue"'
          properties:
            link: .web_url
            description: .description
            createdAt: .created_at
            closedAt: .closed_at
            updatedAt: .updated_at
            creator: .author.username
            status: .state
            labels: '.labels[]'
        relations:
          service:
            target:
              identifier: .project_id
              blueprint: '"project"'
