initializePortResources: true
port:
  clientId: "{{ from env PORT_CLIENT_ID }}"
  clientSecret: "{{ from env PORT_CLIENT_SECRET }}"
eventListener:
  type: POLLING
integration:
  identifier: my_azure_devops_integration
  type: "azure-devops"
  config:
    organizationUrl: "{{ from env ORGANIZATION_URL }}"
    personalAccessToken: "{{ from env PERSONAL_ACCESS_TOKEN }}"
