# This is an example configuration file for the integration service.
# Please copy this file to config.yaml file in the integration folder and edit it to your needs.
initializePortResources: true
scheduledResyncInterval: 60
port:
  clientId: "{{ from env PORT_CLIENT_ID }}"  # Can be loaded via environment variable: PORT_CLIENT_ID
  clientSecret: "{{ from env PORT_CLIENT_SECRET }}"  # Can be loaded via environment variable: PORT_CLIENT_SECRET
  baseUrl: http://localhost:3000  # Can be loaded via environment variable: PORT_BASE_URL
# The event listener to use for the integration service.
eventListener:
  type: POLLING
integration:
  # The identifier of this integration instance.
  identifier: portOceanSentryIntegration
  # The type of the integration.
  type: sentry
  config:
    sentryHost: "{{ from env SENTRY_HOST }}"
    sentryToken: "{{ from env SENTRY_TOKEN }}"
    sentryOrganization: "{{ from env SENTRY_ORGANIZATION }}"
