createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"launchDarklyProject"'
          properties:
            tags: .tags
            link: ("https://app.launchdarkly.com" + ._links.self.href | tostring)
  - kind: flag
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"launchDarklyFeatureFlag"'
          properties:
            kind: .kind
            description: .description
            creationDate: '.creationDate |  (strptime("%Y-%m-%d %H:%M:%S") | strftime("%Y-%m-%dT%H:%M:%SZ"))'
            includeInSnippet: .includeInSnippet
            clientSideAvailability: .clientSideAvailability
            temporary: .temporary
            tags: .tags
            maintainer: ._maintainer
            environments: .environments
            variations: .variations
            customProperties: .customProperties
            archived: .archived
          relations:
            project: .__projectKey
  - kind: auditlog
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ._id
          title: .titleVerb
          blueprint: '"launchDarklyAuditLog"'
          properties:
            accountId: ._accountId
            eventDate: '.date |  (strptime("%Y-%m-%d %H:%M:%S") | strftime("%Y-%m-%dT%H:%M:%SZ"))'
            kind: .kind
            targetResource: .name
            link: ("https://app.launchdarkly.com/" + ._links.canonical.href | tostring)
            shortDescription: .shortDescription
            member: .member
            accessDetails: .accesses
          relations:
            project: 'select(.kind | IN("project")) | .accesses[] | .resource | split("/") | .[-1]'
  - kind: environment
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"launchDarklyEnvironment"'
          properties:
            defaultTtl: .defaultTtl
            secureMode: .secureMode
            defaultTrackEvents: .defaultTrackEvents
            requireComments: .requireComments
            confirmChanges: .confirmChanges
            tags: .tags
            critical: .critical
          relations:
            project: .__projectKey
