createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"launchDarklyProject"'
          properties:
            tags: .tags
            link: ("https://app.launchdarkly.com" + ._links.self.href | tostring)
  - kind: flag
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"launchDarklyFeatureFlag"'
          properties:
            kind: .kind
            description: .description
            creationDate: .creationDate / 1000 | strftime("%Y-%m-%dT%H:%M:%SZ")
            includeInSnippet: .includeInSnippet
            clientSideAvailability: .clientSideAvailability
            temporary: .temporary
            tags: .tags
            maintainer: ._maintainer | .firstName + " " + .lastName
            maintainerEmail: ._maintainer.email
            deprecated: .deprecated
            variations: .variations
            customProperties: .customProperties
            archived: .archived
          relations:
            environments: .environments | keys
  - kind: auditlog
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ._id
          title: .titleVerb
          blueprint: '"launchDarklyAuditLog"'
          properties:
            accountId: ._accountId
            eventDate: .date / 1000 | strftime("%Y-%m-%dT%H:%M:%SZ")
            kind: .kind
            targetResource: .name
            link: ("https://app.launchdarkly.com" + ._links.canonical.href | tostring)
            shortDescription: .shortDescription
            member: .member
            accessDetails: .accesses
          relations:
            project: 'select(.kind | IN("project","flag")) | .accesses[] | .resource | split("proj/") | .[-1] | split(":") | .[0]'
  - kind: environment
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"launchDarklyEnvironment"'
          properties:
            defaultTtl: .defaultTtl
            secureMode: .secureMode
            defaultTrackEvents: .defaultTrackEvents
            requireComments: .requireComments
            confirmChanges: .confirmChanges
            tags: .tags
            critical: .critical
          relations:
            project: .__projectKey
