initializePortResources: true
port:
  clientId: "{{ from env PORT_CLIENT_ID }}" # Can be loaded via environment variable: PORT_CLIENT_ID, if both are set, the environment variable will be used.
  clientSecret: "{{ from env PORT_CLIENT_SECRET }}" # Can be loaded via environment variable: PORT_CLIENT_SECRET, if both are set, the environment variable will be used.
# The event listener to use for the integration service.
eventListener:
  type: POLLING
integration:
  # The name of the integration.
  identifier: "my_gitlab_integration"
  # The type of the integration.
  type: "gitlab"
  # The configuration of the integration.
  config:
    tokenMapping: "{{ from env TOKEN_MAPPING }}"
