createMissingRelatedEntities: true
resources:
  - kind: newRelicAlert
    selector:
      query: 'true'
      NewRelicTypes: ['ISSUE']
    port:
      entity:
        mappings:
          blueprint: '"newRelicAlert"'
          identifier: .issueId
          title: .title[0]
          properties:
              priority: .priority
              state: .state
              sources: .sources
              conditionName: .conditionName
              alertPolicyNames: .policyName
              activatedAt: .activatedAt
          relations:
              newRelicService: .newRelicService.entity_guids
  - kind: newRelicService
    selector:
      query: 'true'
      NewRelicTypes: ['SERVICE', 'APPLICATION']
      RelationIdentifier: 'newRelicService'
      EntityQueryFilter: "type in ('SERVICE','APPLICATION')"
    port:
      entity:
        mappings:
          blueprint: '"newRelicService"'
          identifier: .guid
          title: .name
          properties:
            has_apm: 'if .domain | contains("APM") then "true" else "false" end'
            link: .permalink
            open_issues_count: .open_issues_count
            reporting: .reporting
            tags: .tags
            domain: .domain
            type: .type
