groups:
  params:
    scope: 'all'
    owned: true
  additional_data:
    # - projects
    # - members


projects:
  params:
    owned: true
  additional_data:
    - languages


merge_requests:
  params:
    scope: 'all'
    state: 'opened'
  additional_data:
    # - approvals


issues:
  params:
    scope: 'all'
  additional_data:
    # - notes
    # - assignees
    # - labels


events:
  - push
  - tag_push
  - issue
  - note
  - merge_request
  - wiki_page
  - pipeline
  - job
  - deployment
  - feature_flag
  - release
  - project_token
  - group_token
