initializePortResources: true
port:
  clientId: '{{ from env PORT_CLIENT_ID }}'
  clientSecret: '{{ from env PORT_CLIENT_SECRET }}'
eventListener:
  type: POLLING
integration:
  identifier: my-terraform-cloud-integration
  type: terraform_cloud
  config:
    terraformHost: '{{ from env TERRAFORM_HOST }}'
    terraformToken: '{{ from env TERRAFORM_TOKEN }}'
    appHost: '{{ from env APP_HOST }}'