name: Apply release

on:
  workflow_run:
    workflows:
      - Release framework
    types:
      - completed
  workflow_dispatch:

jobs:
  create_branch_and_open_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Get package version
        id: version
        run: |
          version=$(poetry search port-ocean | grep port-ocean | sed 's/.*(\(.*\))/\1/')
          pr_name="Release ${version}"
          branch_name="release-${version}"
          echo "Branch Name: $branch_name"
          echo "PR Name: $pr_name"
          echo "pr_name=$pr_name" >> $GITHUB_OUTPUT
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Apply changes
        run: |
          git checkout -b ${{ steps.version.outputs.branch_name }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          ./scripts/bump-all.sh ${{ steps.version.outputs.version }}

          git push origin ${{ steps.version.outputs.branch_name }}

      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Propose changes"
          title: ${{ steps.version.outputs.pr_name }}
          body: "This pull request includes changes made in the feature branch."
