name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get list of changed files
        id: changed-files
        uses: tj-actions/changed-files@v44.5.2
      - name: Set matrix
        id: set-matrix
        run: |
          changed_folders=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep '^integrations/' | cut -d'/' -f1,2 | sort | uniq)
          other_changes=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -v '^integrations/' | wc -l)
          if [ "$other_changes" -ne 0 ]; then
            # Add the root directory to the matrix if there are changes outside the integrations folder
            changed_folders=$(echo -e "$changed_folders\n.")
          fi
          
          matrix=$(echo "$changed_folders" | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  lint:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint
        run: |
          cd ${{ matrix.folder }}
          make install
          make lint
