name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Lint
        run: |
          make install/all
          make lint/all
