name: Validate integration files

on:
  pull_request:
    paths:
      - 'integrations/**'

jobs:
  validate-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install toml-cli
      run: |
        pip install toml-cli

    - name: Check Ocean version 🌊
      run: |
        changed_dirs=$(git diff --name-only origin/main origin/${{ github.head_ref }} | grep 'integrations/' | cut -d'/' -f 1,2 | sort -u)
        package_version=$(curl -s https://pypi.org/pypi/port-ocean/json | jq -r '.info.version')
        for dir in $changed_dirs; do
          pyproject_file=$(find $dir -name 'pyproject.toml' -not -path "**/.venv/*")
          if [ -n "$pyproject_file" ]; then
            installed_version=$(toml get  tool.poetry.dependencies.port_ocean.version --toml-path $pyproject_file)
            is_version_updated=$(python -c "from packaging import version;print(version.parse('$installed_version'.lstrip('^')) >= version.parse('$package_version'))")
            
            if [ "$is_version_updated" = "False" ]; then
              echo "ERROR: Ocean version in $pyproject_file is not updated to latest version -> $package_version"
              exit 1
            else
              echo "Ocean version is valid in $pyproject_file"
            fi      
          fi
        done
