name: Verify Docs Build

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "ready_for_review"
      - "converted_to_draft"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Test successful docs production build
    defaults:
      run:
        working-directory: docs/framework-guides/
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: docs/framework-guides/package-lock.json
      - run: npm ci
      - name: Build
        run: npm run build

  build-api-docs:
    runs-on: ubuntu-latest
    name: Test successful api-docs production build
    defaults:
      run:
        working-directory: docs/api-docs
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Make install and build
        run: |
          make install
          make build
